{"uid":"3ffc9ed2b66d5e65","name":"Checking if the book information from the get request matches the books in the list","fullName":"tests.api_tests.book_store_test.TestBookStore#test_comparing_book_information_from_get_request_and_book_list","historyId":"2c2a8de369c826801c0b3fd34ffaa713","time":{"start":1724663777843,"stop":1724663777843,"duration":0},"status":"failed","statusMessage":"AssertionError: 406","statusTrace":"@pytest.fixture(scope='function', autouse=True)\n    def account_setup():\n        account_api = AccountAPI()\n>       user_id = account_api.create_user()\n\ntests/api_tests/conftest.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices/account/api_account.py:25: in create_user\n    self.assert_response_status_code(response, 201)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.account.api_account.AccountAPI object at 0x7f718f07d8e0>\nresponse = <Response [406]>, status_code = 201\n\n    def assert_response_status_code(self, response, status_code):\n        with allure.step(f\"Check response status code is {status_code}\"):\n>           assert response.status_code == status_code, response.status_code\nE           AssertionError: 406\n\nutils/helper.py:14: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1724663775461,"stop":1724663775653,"duration":192},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"account_setup","time":{"start":1724663777844,"stop":1724663778147,"duration":303},"status":"failed","statusMessage":"AssertionError: 406\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/tests/api_tests/conftest.py\", line 8, in account_setup\n    user_id = account_api.create_user()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/services/account/api_account.py\", line 25, in create_user\n    self.assert_response_status_code(response, 201)\n  File \"/usr/workspace/utils/helper.py\", line 14, in assert_response_status_code\n    assert response.status_code == status_code, response.status_code\n","steps":[{"name":"Create user","time":{"start":1724663777844,"stop":1724663778147,"duration":303},"status":"failed","statusMessage":"AssertionError: 406\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/services/account/api_account.py\", line 25, in create_user\n    self.assert_response_status_code(response, 201)\n  File \"/usr/workspace/utils/helper.py\", line 14, in assert_response_status_code\n    assert response.status_code == status_code, response.status_code\n","steps":[{"name":"Check response status code is 201","time":{"start":1724663778147,"stop":1724663778147,"duration":0},"status":"failed","statusMessage":"AssertionError: 406\n","statusTrace":"  File \"/usr/workspace/utils/helper.py\", line 14, in assert_response_status_code\n    assert response.status_code == status_code, response.status_code\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"feature","value":"Book Store"},{"name":"epic","value":"API Tests"},{"name":"parentSuite","value":"tests.api_tests"},{"name":"suite","value":"book_store_test"},{"name":"subSuite","value":"TestBookStore"},{"name":"host","value":"db15b8e47f3f"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.api_tests.book_store_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"3ffc9ed2b66d5e65.json","parameterValues":[]}