{"uid":"46ba6261e9dd3771","name":"Information about the user and books in his profile","fullName":"tests.api_tests.account_test.TestAccount#test_get_user","historyId":"2a24c48e4b37b6cc6ab23bf31ffe4924","time":{"start":1724663280482,"stop":1724663280482,"duration":0},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for TokenResponse\ntoken\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/string_type\nexpires\n  Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/datetime_type","statusTrace":"@pytest.fixture(scope='function', autouse=True)\n    def account_setup():\n        account_api = AccountAPI()\n        user_id = account_api.create_user()\n>       token = account_api.generate_user_token()\n\ntests/api_tests/conftest.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.account.api_account.AccountAPI object at 0x7efe84fc4a70>\n\n    @allure.step(\"Generate user token\")\n    def generate_user_token(self):\n        response = requests.post(\n            url=self.endpoints.generate_token,\n            json=self.payloads.username_password\n        )\n        self.assert_response_status_code(response, 200)\n        self.attach_response(response.json())\n        with allure.step(\"Validation generate user token model\"):\n>           model = TokenResponse(**response.json())\nE           pydantic_core._pydantic_core.ValidationError: 2 validation errors for TokenResponse\nE           token\nE             Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\nE               For further information visit https://errors.pydantic.dev/2.8/v/string_type\nE           expires\nE             Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]\nE               For further information visit https://errors.pydantic.dev/2.8/v/datetime_type\n\nservices/account/api_account.py:40: ValidationError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1724663279767,"stop":1724663279940,"duration":173},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"account_setup","time":{"start":1724663280483,"stop":1724663281939,"duration":1456},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for TokenResponse\ntoken\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/string_type\nexpires\n  Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/datetime_type\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/tests/api_tests/conftest.py\", line 9, in account_setup\n    token = account_api.generate_user_token()\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/services/account/api_account.py\", line 40, in generate_user_token\n    model = TokenResponse(**response.json())\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pydantic/main.py\", line 193, in __init__\n    self.__pydantic_validator__.validate_python(data, self_instance=self)\n","steps":[{"name":"Create user","time":{"start":1724663280483,"stop":1724663281150,"duration":667},"status":"passed","steps":[{"name":"Check response status code is 201","time":{"start":1724663281150,"stop":1724663281150,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Attach response","time":{"start":1724663281150,"stop":1724663281150,"duration":0},"status":"passed","steps":[],"attachments":[{"uid":"3fe19fca71f370cb","name":"API Response","source":"3fe19fca71f370cb.json","type":"application/json","size":102}],"parameters":[{"name":"response","value":"{'userID': '86c93d5a-365a-4025-b253-7e535b331760', 'username': 'Test123!3', 'books': []}"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},{"name":"Validation create user model","time":{"start":1724663281150,"stop":1724663281150,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},{"name":"Generate user token","time":{"start":1724663281151,"stop":1724663281939,"duration":788},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for TokenResponse\ntoken\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/string_type\nexpires\n  Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/datetime_type\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/services/account/api_account.py\", line 40, in generate_user_token\n    model = TokenResponse(**response.json())\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pydantic/main.py\", line 193, in __init__\n    self.__pydantic_validator__.validate_python(data, self_instance=self)\n","steps":[{"name":"Check response status code is 200","time":{"start":1724663281937,"stop":1724663281937,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Attach response","time":{"start":1724663281938,"stop":1724663281938,"duration":0},"status":"passed","steps":[],"attachments":[{"uid":"ad105a7dd7446935","name":"API Response","source":"ad105a7dd7446935.json","type":"application/json","size":110}],"parameters":[{"name":"response","value":"{'token': None, 'expires': None, 'status': 'Failed', 'result': 'User authorization failed.'}"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},{"name":"Validation generate user token model","time":{"start":1724663281938,"stop":1724663281938,"duration":0},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for TokenResponse\ntoken\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/string_type\nexpires\n  Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/datetime_type\n","statusTrace":"  File \"/usr/workspace/services/account/api_account.py\", line 40, in generate_user_token\n    model = TokenResponse(**response.json())\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pydantic/main.py\", line 193, in __init__\n    self.__pydantic_validator__.validate_python(data, self_instance=self)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":1,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":8,"attachmentsCount":2,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"feature","value":"Account"},{"name":"epic","value":"API Tests"},{"name":"severity","value":"critical"},{"name":"parentSuite","value":"tests.api_tests"},{"name":"suite","value":"account_test"},{"name":"subSuite","value":"TestAccount"},{"name":"host","value":"d8fe5808a238"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.api_tests.account_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"46ba6261e9dd3771.json","parameterValues":[]}